In [30]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

from bs4 import BeautifulSoup

import pandas as pd
import time

In [39]:
roles = [

    "data-analyst",
    "business-analyst",
    "data-engineer",
    "data-scientist",
    "power-bi-developer",

    "python-developer",
    "java-developer",
    "full-stack-developer",

    "software-tester",
    "automation-tester",
    "selenium-tester",
    "qa-engineer",
    "sdet",

    "devops-engineer",
    "cloud-engineer",

    "cyber-security-analyst",

    "project-manager",

    "fresher-jobs",

    "associate-software-engineer"
]

In [40]:
# Launch browser

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

In [41]:
# Main Scraping Loop

all_jobs = []

for role in roles:

    print(f"\nStarting role: {role}")

    for page in range(1, 21):

        if page == 1:

            url = f"https://www.naukri.com/{role}-jobs-in-india"

        else:

            url = f"https://www.naukri.com/{role}-jobs-in-india-{page}"


        print("Opening:", url)

        driver.get(url)

        time.sleep(4)

        soup = BeautifulSoup(
            driver.page_source,
            "html.parser"
        )

        job_cards = soup.find_all(
            "div",
            class_="srp-jobtuple-wrapper"
        )

        print("Jobs found:", len(job_cards))


        for card in job_cards:

            # Job Title
            title_tag = card.find("a", class_="title")

            # Company Name
            company_tag = card.find("a", class_="comp-name")

            # Experience
            exp_tag = card.find("span", class_="expwdth")

            # Salary
            sal_tag = card.find("span", class_="sal")

            # Location
            loc_tag = card.find("span", class_="locWdth")

            # Skills
            skill_tags = card.find_all(
                "li",
                class_="tag-li"
            )

            # Posted Date
            posted_tag = card.find(
                "span",
                class_="job-post-day"
            )

            # Description
            desc_tag = card.find(
                "span",
                class_="job-desc"
            )

            # Rating
            rating_tag = card.find(
                "span",
                class_="main-2"
            )

            # Reviews
            review_tag = card.find(
                "a",
                class_="review ver-line"
            )

            # Apply Link
            link = (
                title_tag["href"]
                if title_tag and title_tag.has_attr("href")
                else None
            )

            # Convert skills list to string
            skills = ", ".join(
                [
                    s.get_text(strip=True)
                    for s in skill_tags
                ]
            )

            # Store Data
            all_jobs.append({

                "Portal_Name": "Naukri",

                "Role_Search": role,

                "Job_Title":
                title_tag.get_text(strip=True)
                if title_tag else None,

                "Company_Name":
                company_tag.get_text(strip=True)
                if company_tag else None,

                "Experience_Required":
                exp_tag.get_text(strip=True)
                if exp_tag else None,

                "Salary":
                sal_tag.get_text(strip=True)
                if sal_tag else None,

                "Location":
                loc_tag.get_text(strip=True)
                if loc_tag else None,

                "Skills_Required":
                skills,

                "Posted_Date":
                posted_tag.get_text(strip=True)
                if posted_tag else None,

                "Job_Description":
                desc_tag.get_text(strip=True)
                if desc_tag else None,

                "Company_Rating":
                rating_tag.get_text(strip=True)
                if rating_tag else None,

                "Reviews_Count":
                review_tag.get_text(strip=True)
                if review_tag else None,

                "Job_Type": None,

                "Company_Size": None,

                "Industry": None,

                "Apply_Link": link
            })

print("Scraping completed")

Starting role: data-analyst
Opening: https://www.naukri.com/data-analyst-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-12
Jobs found: 19
Opening: https://www.naukri.com/data-analyst-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/data-analyst-jobs-in-india-20
Jobs found: 20

Starting role: business-analyst
Opening: https://www.naukri.com/business-analyst-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/business-analyst-jobs-in-india-20
Jobs found: 20

Starting role: data-engineer
Opening: https://www.naukri.com/data-engineer-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/data-engineer-jobs-in-india-20
Jobs found: 20

Starting role: data-scientist
Opening: https://www.naukri.com/data-scientist-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-17
Jobs found: 19
Opening: https://www.naukri.com/data-scientist-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/data-scientist-jobs-in-india-20
Jobs found: 20

Starting role: power-bi-developer
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/power-bi-developer-jobs-in-india-20
Jobs found: 20

Starting role: python-developer
Opening: https://www.naukri.com/python-developer-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/python-developer-jobs-in-india-20
Jobs found: 20

Starting role: java-developer
Opening: https://www.naukri.com/java-developer-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-8
Jobs found: 19
Opening: https://www.naukri.com/java-developer-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-16
Jobs found: 19
Opening: https://www.naukri.com/java-developer-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-18
Jobs found: 19
Opening: https://www.naukri.com/java-developer-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/java-developer-jobs-in-india-20
Jobs found: 20

Starting role: full-stack-developer
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/full-stack-developer-jobs-in-india-20
Jobs found: 20

Starting role: software-tester
Opening: https://www.naukri.com/software-tester-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/software-tester-jobs-in-india-20
Jobs found: 20

Starting role: automation-tester
Opening: https://www.naukri.com/automation-tester-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/automation-tester-jobs-in-india-20
Jobs found: 20

Starting role: selenium-tester
Opening: https://www.naukri.com/selenium-tester-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/selenium-tester-jobs-in-india-20
Jobs found: 20

Starting role: qa-engineer
Opening: https://www.naukri.com/qa-engineer-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-7
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-8
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-9
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-10
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-11
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-12
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-13
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-14
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-15
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-16
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-17
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-18
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-19
Jobs found: 20
Opening: https://www.naukri.com/qa-engineer-jobs-in-india-20
Jobs found: 20

Starting role: sdet
Opening: https://www.naukri.com/sdet-jobs-in-india
Jobs found: 20
Opening: https://www.naukri.com/sdet-jobs-in-india-2
Jobs found: 20
Opening: https://www.naukri.com/sdet-jobs-in-india-3
Jobs found: 20
Opening: https://www.naukri.com/sdet-jobs-in-india-4
Jobs found: 20
Opening: https://www.naukri.com/sdet-jobs-in-india-5
Jobs found: 20
Opening: https://www.naukri.com/sdet-jobs-in-india-6
Jobs found: 20
Opening: https://www.naukri.com/sdet-jobs-in-india-7
Jobs found: 20

In [42]:
driver.quit()

In [43]:
# creating data frame

df = pd.DataFrame(all_jobs)

print(df.shape)

df.head()

(7592, 16)

,Portal_Name,Role_Search,Job_Title,Company_Name,Experience_Required,Salary,Location,Skills_Required,Posted_Date,Job_Description,Company_Rating,Reviews_Count,Job_Type,Company_Size,Industry,Apply_Link
0,Naukri,data-analyst,Data Analyst,Capgemini,4-9 Yrs,None,"Hybrid - Chennai, Delhi / NCR, Mumbai (All Areas)","Power Bi, Data Analysis, Data Visualization, T...",1 day ago,Required Skills & Qualifications: . Bachelors ...,3.6,53623 Reviews,None,None,None,https://www.naukri.com/job-listings-data-analy...
1,Naukri,data-analyst,Data Analyst,Airtel Payments Bank,2-5 Yrs,None,Gurugram,"Power Bi, SQL, Python, Oracle SQL, Quicksight,...",1 week ago,"Job Description 1- Extract, analyze, and valid...",3.8,1463 Reviews,None,None,None,https://www.naukri.com/job-listings-data-analy...
2,Naukri,data-analyst,Data Analyst,Sbicap Securities,None,10-15 Lacs PA,Mumbai,"Data Analysis, Predictive Modeling, Statistica...",1 week ago,Key Competencies: . Strong proficiency in Pyth...,3.6,2287 Reviews,None,None,None,https://www.naukri.com/job-listings-data-analy...
3,Naukri,data-analyst,Data Analyst,Wonderla Holidays,3-5 Yrs,"50,000-80,000 PA",Bengaluru,"D2C, Google Data Studio, R, Google Analytics, ...",1 week ago,Preferred candidate profile,4.4,396 Reviews,None,None,None,https://www.naukri.com/job-listings-data-analy...
4,Naukri,data-analyst,Data Analyst,Snapdeal,1-6 Yrs,None,Gurugram,"master data, python, metadata, data analysis, ...",3+ weeks ago,Providing technical expertise in data storage ...,3.7,668 Reviews,None,None,None,https://www.naukri.com/job-listings-data-analy...

In [47]:
#  Remove duplicate rows

df.drop_duplicates(inplace=True)


# Remove rows with missing critical fields

df.dropna(
    subset=[
        "Job_Title",
        "Company_Name",
        "Location"
    ],
    inplace=True
)


# Clean important text columns

text_cols = [

    "Portal_Name",

    "Role_Search",

    "Job_Title",

    "Company_Name",

    "Experience_Required",

    "Salary",

    "Location",

    "Skills_Required",

    "Posted_Date",

    "Job_Description",

    "Company_Rating",

    "Reviews_Count",

    "Job_Type",

    "Company_Size",

    "Industry",

    "Apply_Link"
]


for col in text_cols:

    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
    )


# Replace 'None' strings with actual null values

df.replace(
    ["None", "nan", ""],
    pd.NA,
    inplace=True
)


# Reset dataframe index

df.reset_index(
    drop=True,
    inplace=True
)


# Check final dataset shape

print(df.shape)


# Check missing values

print(df.isnull().sum())


# Preview dataset

df.head()

(7520, 16)
Portal_Name               0
Role_Search               0
Job_Title                 0
Company_Name              0
Experience_Required      64
Salary                 6431
Location                  0
Skills_Required         233
Posted_Date               0
Job_Description          56
Company_Rating         1540
Reviews_Count          1540
Job_Type               7520
Company_Size           7520
Industry               7520
Apply_Link                0
dtype: int64

,Portal_Name,Role_Search,Job_Title,Company_Name,Experience_Required,Salary,Location,Skills_Required,Posted_Date,Job_Description,Company_Rating,Reviews_Count,Job_Type,Company_Size,Industry,Apply_Link
0,Naukri,data-analyst,Data Analyst,Capgemini,4-9 Yrs,<NA>,"Hybrid - Chennai, Delhi / NCR, Mumbai (All Areas)","Power Bi, Data Analysis, Data Visualization, T...",1 day ago,Required Skills & Qualifications: . Bachelors ...,3.6,53623 Reviews,<NA>,<NA>,<NA>,https://www.naukri.com/job-listings-data-analy...
1,Naukri,data-analyst,Data Analyst,Airtel Payments Bank,2-5 Yrs,<NA>,Gurugram,"Power Bi, SQL, Python, Oracle SQL, Quicksight,...",1 week ago,"Job Description 1- Extract, analyze, and valid...",3.8,1463 Reviews,<NA>,<NA>,<NA>,https://www.naukri.com/job-listings-data-analy...
2,Naukri,data-analyst,Data Analyst,Sbicap Securities,<NA>,10-15 Lacs PA,Mumbai,"Data Analysis, Predictive Modeling, Statistica...",1 week ago,Key Competencies: . Strong proficiency in Pyth...,3.6,2287 Reviews,<NA>,<NA>,<NA>,https://www.naukri.com/job-listings-data-analy...
3,Naukri,data-analyst,Data Analyst,Wonderla Holidays,3-5 Yrs,"50,000-80,000 PA",Bengaluru,"D2C, Google Data Studio, R, Google Analytics, ...",1 week ago,Preferred candidate profile,4.4,396 Reviews,<NA>,<NA>,<NA>,https://www.naukri.com/job-listings-data-analy...
4,Naukri,data-analyst,Data Analyst,Snapdeal,1-6 Yrs,<NA>,Gurugram,"master data, python, metadata, data analysis, ...",3+ weeks ago,Providing technical expertise in data storage ...,3.7,668 Reviews,<NA>,<NA>,<NA>,https://www.naukri.com/job-listings-data-analy...

In [49]:
# final cleaned dataset

df.to_csv(
    "../data/cleaned/naukri_final_dataset.csv",
    index=False
)

print("Final Naukri dataset exported successfully")

Final Naukri dataset exported successfully